In [74]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt


In [75]:
train = pd.read_csv("uploads.csv")

In [76]:
print(train.shape)

(692, 10)


In [77]:
x =np.array(train.drop(['Fake Or Not Category'],axis = 1))

In [78]:
x

array([[  1,   1,  37, ..., 838,  26,  53],
       [  2,   2,  63, ..., 349,  37,  58],
       [  3,   3,  10, ..., 271,  73,  11],
       ...,
       [690, 690,  87, ..., 282,  85,  40],
       [691, 691,  24, ..., 554,  56,  97],
       [692, 692,  68, ..., 299,  72,  91]], dtype=int64)

In [79]:
y = np.array(train['Fake Or Not Category'])

In [80]:
y

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [82]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .25,random_state = 2)

In [83]:
rf = RandomForestClassifier()

In [84]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [85]:
y_test_predict = rf.predict(x_test)

In [86]:
Accuracy_test = metrics.accuracy_score(y_test_predict,y_test)

In [87]:
Accuracy_test 

1.0

In [92]:
x[0].reshape(1,-1).shape

(1, 9)

In [93]:
rf.predict(x[0].reshape(1,-1))

array([1], dtype=int64)

In [94]:
import pickle 

In [95]:
pickle.dump(rf,open('fake.pkl','wb'))

In [96]:
pickled_model = pickle.load(open('fake.pkl','rb'))

In [97]:
pickled_model.predict(x[0].reshape(1,-1))

array([1], dtype=int64)